

class RandomGenerator{
	constructor(max, min){
		this.defaultValues = {
			max: 10,
			min: 1,
		}
		this.max = max;
		this.min = min;
		this.randomNumber;
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate(){
		this.randomNumber = Math.floor(Math.random() * this.max) + this.min;
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange(){
		var numberRanges = {}

		numberRanges.min = this.max;
		numberRanges.max = this. min;
		
		return numberRanges;
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		//return the random number that was generated by generate()
		return this.randomNumber;
	}
}
